"""Add image_filename column to Oprema

Revision ID: 41cf3dc87cc1
Revises: b93c970704a6
Create Date: 2025-05-22 19:22:50.926977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cf3dc87cc1'
down_revision = 'b93c970704a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oprema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oprema', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
