"""Add image_filename column to Oprema(improved)

Revision ID: 525c9bc9f0c6
Revises: 41cf3dc87cc1
Create Date: 2025-05-22 19:53:59.955916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525c9bc9f0c6'
down_revision = '41cf3dc87cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oprema', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oprema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
