"""Rename kategorija to category

Revision ID: b93c970704a6
Revises: 
Create Date: 2025-05-20 00:21:57.073071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93c970704a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oprema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_number', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('serial_number', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('model_number', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('supplier', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_of_acquisition', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('warranty_until', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('purchase_value', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('project', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('service_period', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('next_service', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('labaratory_assistant', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('professor', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('available', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=False))
        batch_op.drop_column('kategorija')
        batch_op.drop_column('kolicina')
        batch_op.drop_column('naziv')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oprema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naziv', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('kolicina', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('kategorija', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('note')
        batch_op.drop_column('available')
        batch_op.drop_column('category')
        batch_op.drop_column('location')
        batch_op.drop_column('professor')
        batch_op.drop_column('labaratory_assistant')
        batch_op.drop_column('next_service')
        batch_op.drop_column('service_period')
        batch_op.drop_column('project')
        batch_op.drop_column('purchase_value')
        batch_op.drop_column('warranty_until')
        batch_op.drop_column('date_of_acquisition')
        batch_op.drop_column('supplier')
        batch_op.drop_column('model_number')
        batch_op.drop_column('serial_number')
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('inventory_number')

    # ### end Alembic commands ###
