"""Removed professor

Revision ID: f570b7630cee
Revises: 6ac2fec940c6
Create Date: 2025-05-23 15:59:38.287429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f570b7630cee'
down_revision = '6ac2fec940c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oprema', schema=None) as batch_op:
        batch_op.drop_column('professor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oprema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
