name: Flask CI kod

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest pytest-mock pytest-flask

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U admin; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Setup test database
        run: |
          PGPASSWORD=password psql -U admin -h localhost -d postgres -c "DROP DATABASE IF EXISTS rentalab_test;"
          PGPASSWORD=password psql -U admin -h localhost -d postgres -c "CREATE DATABASE rentalab_test;"

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/ -v -s
        env:
          PGPASSWORD: password
